---
development:
  cloud_name: betascript
  api_key: '236167296352944'
  api_secret: A55UrgzroUtknICvPQumHzhlkb8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: betascript
  api_key: '236167296352944'
  api_secret: A55UrgzroUtknICvPQumHzhlkb8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: betascript
  api_key: '236167296352944'
  api_secret: A55UrgzroUtknICvPQumHzhlkb8
  enhance_image_tag: true
  static_image_support: false
