# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1f363613f4f537f5bd5295bf62fdf23bb0e23099f68de7896063a39fa78cca855dd632c0b2904247262c99c92a3466428bd095659ca4a2f72f09470996ead5

test:
  secret_key_base: ed35f6e0d533c91d4e6f3421e4f13812f653987d5a786608d75014920d2e0fc1696760c9f899bdf1be879bae5872fb3474907f09ec17fbb0de67cff85ad262a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
